name: Release

on:
  pull_request:
    branches: ['main']
    paths:
      - .github/workflows/release.yml
      - .goreleaser.yaml
  push:
    tags: ['v*.*.*']

permissions:
  contents: read
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - uses: goreleaser/goreleaser-action@v6
        if: github.event_name == 'pull_request'
        with:
          version: '~> v2'
          args: release --snapshot
        env:
          GITHUB_TOKEN: ${{ github.token }}
          # Disable the monorepo feature
          GORELEASER_CURRENT_TAG: v0.0.1
          GORELEASER_PREVIOUS_TAG: v0.0.1-alpha

      - uses: goreleaser/goreleaser-action@v6
        if: github.event_name != 'pull_request'
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}

  nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - run: dotnet pack --configuration Release --output nupkgs

      - name: Publish to GitHub Packages
        if: github.event_name != 'pull_request'
        run: |
          dotnet nuget push 'nupkgs/UnMango.Ux.*.nupkg' \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --skip-duplicate

      - name: Publish to NuGet.org
        if: github.event_name != 'pull_request'
        run: |
          dotnet nuget push 'nupkgs/UnMango.Ux.*.nupkg' \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --skip-duplicate
